version: "3.1"
 
volumes: 
  dev_mysql_data:

services:
    mysql:
        image: mysql:5.6
        volumes:
          - dev_mysql_data:/var/lib/mysql 
        environment:
          MYSQL_ROOT_PASSWORD: docker
        ports:
            - "3306:3306"
 